Various approaches of converting text into Vector

1. Label Encoding
2. One hot encoding
3. Bag of words
4. TF-IDF4
5. Word Embeddings

# Text Representation - Bag Of Words (BOW)

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("spam_dataset.csv")
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [9]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [11]:
df.shape

(5572, 3)

In [6]:
df['spam']  = df.Category.apply(lambda x: 1 if x == 'spam' else 0)
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [7]:
#Train test split 
from sklearn.model_selection import train_test_split

In [13]:
x_train, x_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size = 0.3)

In [14]:
x_train.shape

(3900,)

In [17]:
x_test.shape

(1672,)

In [19]:
x_train[:4]

661     Under the sea, there lays a rock. In the rock,...
1306    Designation is software developer and may be s...
1484    Purity of friendship between two is not about ...
5306    Ill be at yours in about 3 mins but look out f...
Name: Message, dtype: object

In [20]:
y_train[:4]

661     0
1306    0
1484    0
5306    0
Name: spam, dtype: int64

In [26]:
# Create bag of words representation using CountVectorizer

# Convert a collection of text documents to a matrix of token counts.

from sklearn.feature_extraction.text import CountVectorizer

In [27]:
x_train.values

array(["Under the sea, there lays a rock. In the rock, there is an envelope. In the envelope, there is a paper. On the paper, there are 3 words... '",
       'Designation is software developer and may be she get chennai:)',
       'Purity of friendship between two is not about smiling after reading the forwarded message..Its about smiling just by seeing the name. Gud evng musthu',
       ..., 'Yavnt tried yet and never played original either',
       "Okay. I've seen it. So i should pick it on friday?",
       'Ah poop. Looks like ill prob have to send in my laptop to get fixed cuz it has a gpu problem'],
      dtype=object)

In [28]:
v = CountVectorizer()

x_train_cv = v.fit_transform(x_train.values)
x_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [29]:
x_train_cv.shape

(3900, 7194)

In [34]:
v.get_feature_names_out()[1000:1050]

array(['arestaurant', 'aretaking', 'areyouunique', 'argh', 'argue',
       'arguing', 'argument', 'arise', 'arithmetic', 'arm', 'armand',
       'arms', 'arng', 'arngd', 'arnt', 'around', 'aroundn', 'arr',
       'arrange', 'arranging', 'arrested', 'arrive', 'arrived', 'art',
       'artists', 'arts', 'arty', 'arul', 'arun', 'as', 'asap', 'ashes',
       'ashley', 'ashwini', 'asian', 'asjesus', 'ask', 'askd', 'asked',
       'askin', 'asking', 'asks', 'asleep', 'asp', 'ass', 'assessment',
       'asshole', 'assistance', 'associate', 'asssssholeeee'],
      dtype=object)

In [36]:
v.vocabulary_

{'under': 6642,
 'the': 6335,
 'sea': 5552,
 'there': 6349,
 'lays': 3807,
 'rock': 5406,
 'in': 3433,
 'is': 3530,
 'an': 915,
 'envelope': 2467,
 'paper': 4741,
 'on': 4618,
 'are': 997,
 'words': 7062,
 'designation': 2124,
 'software': 5829,
 'developer': 2142,
 'and': 919,
 'may': 4135,
 'be': 1202,
 'she': 5651,
 'get': 2935,
 'chennai': 1664,
 'purity': 5129,
 'of': 4583,
 'friendship': 2831,
 'between': 1260,
 'two': 6594,
 'not': 4527,
 'about': 720,
 'smiling': 5801,
 'after': 811,
 'reading': 5220,
 'forwarded': 2790,
 'message': 4185,
 'its': 3549,
 'just': 3649,
 'by': 1501,
 'seeing': 5571,
 'name': 4401,
 'gud': 3073,
 'evng': 2528,
 'musthu': 4377,
 'ill': 3403,
 'at': 1057,
 'yours': 7169,
 'mins': 4226,
 'but': 1486,
 'look': 3947,
 'out': 4682,
 'for': 2767,
 'me': 4141,
 'here': 3209,
 'got': 3015,
 'lots': 3967,
 'hair': 3103,
 'dresser': 2308,
 'fr': 2798,
 'china': 1680,
 'freemsg': 2815,
 'claim': 1704,
 'ur': 6697,
 '250': 343,
 'sms': 5808,
 'messages': 4187,
 'text': 6307,
 'ok': 4601,
 'to': 6443,
 '84025': 635,
 'now': 4539,
 'use': 6713,
 'web2mobile': 6909,
 'mates': 4119,
 'etc': 2496,
 'join': 3618,
 'txt250': 6597,
 'com': 1778,
 '50p': 513,
 'wk': 7030,
 'box139': 1378,
 'la32wu': 3755,
 '16': 291,
 'remove': 5306,
 'txtx': 6606,
 'or': 4649,
 'stop': 6026,
 've': 6754,
 'sent': 5600,
 'da': 2015,
 'latest': 3794,
 'version': 6766,
 'project': 5078,
 '8007': 601,
 '25p': 346,
 'alfie': 865,
 'moon': 4308,
 'children': 1676,
 'need': 4436,
 'song': 5855,
 'mob': 4271,
 'tell': 6277,
 'm8s': 4035,
 'txt': 6596,
 'tone': 6469,
 'charity': 1634,
 'nokias': 4506,
 'poly': 4938,
 'polys': 4943,
 'zed': 7187,
 '08701417012': 71,
 'profit': 5074,
 'aight': 839,
 'let': 3846,
 'know': 3728,
 'when': 6960,
 'you': 7162,
 're': 5210,
 'gonna': 2997,
 'around': 1015,
 'usf': 6718,
 'how': 3315,
 'dare': 2032,
 'change': 1622,
 'my': 4384,
 'ring': 5388,
 'yoyyooo': 7174,
 'permissions': 4817,
 'drive': 2314,
 'mac': 4040,
 'usb': 6711,
 'flash': 2717,
 'also': 886,
 'dont': 2269,
 'msg': 4338,
 'reply': 5326,
 'his': 3234,
 'what': 6955,
 'time': 6410,
 'do': 2233,
 'll': 3915,
 'mu': 4353,
 'like': 3869,
 'lt': 4001,
 'gt': 3069,
 'seconds': 5559,
 'oh': 4597,
 'den': 2105,
 'muz': 4381,
 'plan': 4884,
 'liao': 3853,
 'go': 2976,
 'back': 1132,
 'have': 3158,
 'yan': 7129,
 'jiu': 3608,
 'again': 818,
 'camera': 1536,
 'awarded': 1109,
 'sipix': 5741,
 'digital': 2179,
 'call': 1516,
 '09061221066': 174,
 'fromm': 2844,
 'landline': 3771,
 'delivery': 2100,
 'within': 7023,
 '28': 350,
 'days': 2051,
 'all': 872,
 'sounds': 5879,
 'good': 2999,
 'fingers': 2688,
 'makes': 4070,
 'it': 3542,
 'difficult': 2175,
 'type': 6608,
 'we': 6899,
 'currently': 1994,
 'awaiting': 1106,
 'your': 7165,
 'collection': 1771,
 'collect': 1768,
 '08718723815': 128,
 'attend': 1068,
 'driving': 2317,
 'lesson': 3844,
 'many': 4092,
 'times': 6411,
 'which': 6969,
 'day': 2050,
 'free': 2808,
 'can': 1540,
 'cps': 1922,
 'causing': 1593,
 'outages': 4683,
 'conserve': 1847,
 'energy': 2439,
 'urgent': 6700,
 'please': 4900,
 '09061213237': 172,
 'from': 2843,
 '5000': 509,
 'cash': 1580,
 'luxury': 4020,
 'canary': 1543,
 'islands': 3536,
 'holiday': 3264,
 'await': 1105,
 'cs': 1966,
 'sae': 5468,
 'po': 4912,
 'box': 1376,
 '177': 294,
 'm227xy': 4029,
 '150ppm': 283,
 'help': 3198,
 'ask': 1036,
 'if': 3391,
 'working': 7065,
 'tmr': 6437,
 'emigrated': 2426,
 'something': 5844,
 'maybe': 4137,
 '30': 400,
 'was': 6873,
 'bit': 1290,
 'hopeful': 3286,
 'search': 5553,
 'happiness': 3134,
 'main': 4065,
 'sources': 5883,
 'unhappiness': 6654,
 'accept': 735,
 'life': 3860,
 'way': 6895,
 'comes': 1786,
 'will': 6992,
 'find': 2683,
 'every': 2514,
 'moment': 4289,
 'live': 3907,
 'sorry': 5869,
 'de': 2056,
 'went': 6941,
 'shop': 5679,
 'mail': 4062,
 'hey': 3216,
 'jazz': 3585,
 'power': 4987,
 'yoga': 7158,
 'hip': 3231,
 'hop': 3283,
 'kb': 3677,
 'yogasana': 7159,
 'later': 3793,
 'thk': 6370,
 'shld': 5673,
 'ya': 7124,
 'wana': 6859,
 'lessons': 3845,
 'haha': 3099,
 'one': 4621,
 'whole': 6975,
 'stretch': 6051,
 'x2': 7105,
 'going': 2988,
 'that': 6331,
 'poor': 4950,
 'girl': 2953,
 'lmao': 3918,
 'purchase': 5127,
 'stuff': 6074,
 'today': 6448,
 'number': 4551,
 'coming': 1788,
 'dinner': 2190,
 'rite': 5398,
 'dad': 2017,
 'so': 5825,
 'confirm': 1833,
 'wif': 6985,
 'afternoon': 813,
 'love': 3978,
 'goes': 2983,
 'did': 2160,
 'sleep': 5767,
 'hope': 3284,
 'well': 6935,
 'boytoy': 1394,
 'think': 6362,
 'happy': 3135,
 'new': 4464,
 'year': 7138,
 'family': 2602,
 'this': 6369,
 'bring': 1425,
 'stability': 5959,
 'tranquility': 6519,
 'vibrant': 6772,
 'colourful': 1776,
 'wish': 7012,
 'returns': 5367,
 'birthday': 1288,
 'vikky': 6784,
 'yup': 7182,
 'until': 6680,
 'closes': 1734,
 'lor': 3957,
 'haf': 3098,
 'found': 2792,
 'him': 3229,
 'feel': 2635,
 'stupid': 6078,
 'cam': 1533,
 'network': 4457,
 'operator': 4637,
 'service': 5610,
 'visit': 6797,
 '80488': 608,
 'biz': 1296,
 'cant': 1550,
 'believe': 1241,
 'said': 5472,
 'things': 6361,
 'morning': 4314,
 'really': 5230,
 'wanted': 6864,
 'say': 5516,
 'beautiful': 1208,
 'see': 5569,
 'library': 3856,
 'gd': 2913,
 'wah': 6835,
 'fast': 2616,
 'pls': 4906,
 'cme': 1744,
 'want': 6862,
 'hos': 3297,
 '2morow': 372,
 'wil': 6988,
 'her': 3208,
 'dear': 2062,
 'didnt': 2163,
 'any': 944,
 'fyi': 2876,
 'parents': 4752,
 'place': 4881,
 'south': 5884,
 'tampa': 6230,
 'might': 4203,
 'deal': 2058,
 'somewhere': 5848,
 'else': 2415,
 'pick': 4857,
 'phone': 4845,
 'right': 5385,
 'send': 5591,
 'seems': 5574,
 'unnecessarily': 6670,
 'affectionate': 803,
 'part': 4758,
 'nottingham': 4534,
 'hrs': 3326,
 '63miles': 546,
 'thing': 6360,
 'man': 4079,
 'much': 4355,
 'only': 4625,
 'doing': 2255,
 '40mph': 456,
 'ho': 3253,
 'bored': 1358,
 'speed': 5907,
 'dating': 2046,
 'try': 6563,
 'speedchat': 5908,
 '80155': 605,
 'don': 2265,
 'em': 2418,
 'swap': 6172,
 'chatter': 1645,
 'chat80155': 1643,
 'pobox36504w45wq': 4920,
 '150p': 280,
 'rcd': 5205,
 'then': 6343,
 'darren': 2038,
 'oso': 4670,
 'sian': 5710,
 'meet': 4154,
 'lect': 3826,
 'they': 6357,
 'released': 5291,
 'another': 932,
 'italian': 3543,
 'has': 3144,
 'cosign': 1893,
 'option': 4647,
 '2nd': 379,
 'tried': 6543,
 'contact': 1854,
 'won': 7047,
 '1450': 274,
 'prize': 5054,
 '09053750005': 157,
 'b4': 1118,
 '310303': 414,
 '08718725756': 129,
 '140ppm': 272,
 'work': 7063,
 'few': 2651,
 'min': 4212,
 'come': 1784,
 '25': 342,
 'pass': 4765,
 'lar': 3782,
 'thinking': 6365,
 'eatin': 2373,
 'lunch': 4013,
 'anybody': 945,
 'still': 6015,
 'haven': 3160,
 'thought': 6378,
 'up': 6682,
 'tactful': 6206,
 'alex': 864,
 'responsibilities': 5353,
 'some': 5836,
 'them': 6341,
 'told': 6457,
 'accenture': 734,
 'true': 6555,
 'thru': 6389,
 'very': 6768,
 'different': 2174,
 'feeling': 2637,
 'wavering': 6893,
 'decisions': 2073,
 'coping': 1881,
 'with': 7020,
 'same': 5486,
 'individual': 3458,
 'heal': 3174,
 'everything': 2523,
 'arnt': 1014,
 'pissed': 4875,
 'off': 4585,
 'id': 3380,
 'would': 7079,
 'tomorrow': 6467,
 'xxxxxxxxxxxxxx': 7121,
 'win': 6995,
 'newest': 4466,
 'harry': 3143,
 'potter': 4981,
 'order': 4656,
 'phoenix': 4844,
 'book': 1347,
 'answer': 935,
 'questions': 5153,
 'chance': 1620,
 'first': 2702,
 'among': 906,
 'readers': 5218,
 'company': 1797,
 'environment': 2468,
 'terrific': 6299,
 'food': 2758,
 'nice': 4475,
 'hello': 3195,
 'darling': 2036,
 'chat': 1642,
 'why': 6979,
 'sexy': 5625,
 'am': 893,
 'sure': 6153,
 'night': 4481,
 'menu': 4179,
 'noon': 4512,
 'im': 3407,
 'realy': 5232,
 'soz': 5887,
 'imat': 3412,
 'mums': 4364,
 '2nite': 382,
 '2moro': 371,
 'sunshine': 6138,
 'quiz': 5160,
 'wkly': 7034,
 'top': 6487,
 'sony': 5857,
 'dvd': 2351,
 'player': 4895,
 'country': 1908,
 'liverpool': 3910,
 'played': 4894,
 'mid': 4199,
 'week': 6922,
 'ansr': 934,
 '82277': 619,
 '50': 507,
 'sp': 5889,
 'tyrone': 6610,
 'ringtone': 5391,
 'real': 5222,
 'eg': 2395,
 'real1': 5223,
 'pushbutton': 5133,
 'dontcha': 2270,
 'babygoodbye': 1130,
 'golddigger': 2991,
 'webeburnin': 6911,
 '1st': 312,
 'more': 4310,
 'little': 3906,
 'pocy': 4927,
 'bell': 1243,
 'cos': 1892,
 'bak': 1141,
 't4get2text': 6200,
 'wait': 6841,
 'chikku': 1673,
 'il': 3401,
 'aftr': 816,
 'leaving': 3825,
 'soon': 5860,
 'princess': 5043,
 'great': 3047,
 'better': 1259,
 'made': 4051,
 'friday': 2825,
 'stuffed': 6076,
 'myself': 4389,
 'pig': 4868,
 'yesterday': 7148,
 'bleh': 1309,
 'least': 3822,
 'writhing': 7085,
 'pain': 4722,
 'kind': 3708,
 'wont': 7054,
 'anything': 953,
 'awesome': 1111,
 'gate': 2903,
 'charles': 1635,
 'last': 3788,
 'uh': 6618,
 'yeah': 7137,
 'tel': 6273,
 '08712402779': 98,
 'immediately': 3417,
 'as': 1029,
 'waiting': 6844,
 'table': 6202,
 'occupied': 4577,
 'tree': 6539,
 'aathi': 709,
 'lot': 3965,
 'wen': 6938,
 'miss': 4239,
 'someone': 5839,
 'person': 4822,
 'definitely': 2086,
 'special': 5900,
 'keep': 3679,
 'touch': 6502,
 'gdeve': 2914,
 'people': 4802,
 'sight': 5717,
 'remain': 5297,
 'till': 6408,
 'maintain': 4066,
 'ends': 2437,
 'sh': 5629,
 'jas': 3579,
 'home': 3269,
 'watching': 6884,
 'tv': 6586,
 'aiyo': 849,
 'dun': 2344,
 'wan': 6857,
 'eat': 2371,
 'bathe': 1180,
 'already': 883,
 'talents': 6219,
 'date': 2043,
 'next': 4471,
 'aunts': 1084,
 'anniversary': 926,
 'party': 4762,
 'tarpon': 6237,
 'springs': 5948,
 'dunno': 2346,
 'leh': 3835,
 'remember': 5300,
 'mayb': 4136,
 'wat': 6880,
 'meeting': 4156,
 'getting': 2942,
 'even': 2507,
 'making': 4073,
 'money': 4294,
 'enough': 2453,
 'half': 3107,
 'ten': 6287,
 'owe': 4703,
 'give': 2959,
 'massages': 4113,
 'baby': 1129,
 'oil': 4600,
 'fave': 2624,
 'position': 4964,
 'normally': 4522,
 'drink': 2309,
 'water': 6885,
 'daily': 2021,
 'heads': 3171,
 'left': 3829,
 'putting': 5139,
 'should': 5691,
 'ready': 5221,
 'our': 4679,
 'prashanthettan': 5007,
 'mother': 4319,
 'passed': 4766,
 'away': 1110,
 'pray': 5009,
 'nope': 4514,
 'meanwhile': 4148,
 'talk': 6220,
 'make': 4069,
 'greet': 3053,
 'means': 4146,
 'february': 2634,
 'april': 989,
 'stay': 5990,
 'down': 2289,
 'hustle': 3358,
 'forth': 2786,
 'during': 2350,
 'audition': 1077,
 'season': 5555,
 'since': 5734,
 'sister': 5745,
 'moved': 4327,
 'harlem': 3141,
 'seriously': 5608,
 'those': 6374,
 'exact': 2536,
 'nothing': 4531,
 'ever': 2513,
 'easy': 2370,
 'looking': 3951,
 'reason': 5233,
 'take': 6212,
 'risk': 5396,
 'customer': 1999,
 'representative': 5330,
 'freephone': 2816,
 '0808': 56,
 '145': 273,
 '4742': 479,
 '9am': 698,
 '11pm': 252,
 'guaranteed': 3071,
 '1000': 234,
 'havent': 3161,
 'collected': 1769,
 'dough': 2288,
 'control': 1865,
 'no': 4497,
 'didn': 2162,
 'mean': 4143,
 'post': 4971,
 'wrote': 7091,
 'other': 4672,
 'ritten': 5399,
 'sit': 5746,
 'angry': 922,
 'before': 1228,
 'hit': 3236,
 'wasn': 6875,
 'checked': 1653,
 'car': 1558,
 'were': 6944,
 'wouldn': 7081,
 'clean': 1717,
 'fold': 2744,
 'laundry': 3801,
 'bed': 1217,
 'shola': 5677,
 'college': 1773,
 'medicine': 4152,
 'academic': 732,
 'department': 2112,
 'secretary': 5561,
 'current': 1993,
 'situation': 5749,
 'transfer': 6521,
 'check': 1652,
 'sagamu': 5471,
 'lautech': 3803,
 'vital': 6799,
 'completes': 1809,
 'medical': 4151,
 'education': 2385,
 'nigeria': 4479,
 'less': 3843,
 'expensive': 2560,
 'unless': 6667,
 'citizen': 1701,
 'rates': 5196,
 'zealand': 7185,
 'chechi': 1651,
 'tonight': 6474,
 'del': 2090,
 'long': 3944,
 'sum': 6123,
 'lucyxx': 4011,
 'entry': 2463,
 'textpod': 6316,
 '40gb': 455,
 'ipod': 3520,
 'vpod': 6817,
 '81303': 614,
 'ts': 6566,
 'www': 7103,
 'net': 4452,
 'custcare': 1998,
 '08712405020': 101,
 'site': 5747,
 'simulate': 5733,
 'test': 6303,
 'gives': 2961,
 'tough': 6504,
 'readiness': 5219,
 'computer': 1817,
 'fried': 2828,
 'essential': 2493,
 'spares': 5896,
 'because': 1212,
 'fucking': 2855,
 'idiot': 3387,
 'roommates': 5419,
 'looovvve': 3955,
 'running': 5450,
 'full': 2859,
 'had': 3096,
 'these': 6351,
 'started': 5980,
 'sport': 5940,
 'radio': 5167,
 'connection': 1844,
 'coincidence': 1761,
 'dai': 2020,
 'naal': 4394,
 'eruku': 2483,
 'babe': 1126,
 'woo': 7055,
 'hoo': 3278,
 'dude': 2337,
 'wondering': 7052,
 'wow': 7082,
 'tm': 6433,
 'ing': 3468,
 'whenever': 6961,
 'mine': 4218,
 'laughs': 3800,
 'prabha': 4994,
 'soryda': 5875,
 'frm': 2834,
 'heart': 3181,
 'sory': 5874,
 'wrong': 7090,
 'yep': 7144,
 'pretty': 5034,
 'sculpture': 5549,
 'thinkin': 6364,
 'congrats': 1839,
 'treat': 6535,
 'pending': 4799,
 'once': 4620,
 'respect': 5348,
 'mails': 4064,
 'askd': 1037,
 'knw': 3731,
 'tht': 6391,
 'welcome': 6933,
 'uk': 6621,
 'mobile': 4273,
 'giving': 2962,
 'calling': 1529,
 '08719839835': 146,
 'future': 2874,
 'mgs': 4195,
 'billed': 1278,
 'cancel': 1544,
 '89123': 672,
 'mr': 4334,
 'valentine': 6737,
 'yo': 7157,
 'tho': 6373,
 'hardly': 3139,
 'play': 4893,
 'khelate': 3691,
 'kintu': 3713,
 'opponenter': 4640,
 'dhorte': 2152,
 'lage': 3763,
 'thats': 6334,
 'rule': 5444,
 'receiving': 5247,
 'quality': 5146,
 'wins': 7007,
 'admin': 780,
 'building': 1466,
 'slightly': 5776,
 'earlier': 2358,
 'reaching': 5214,
 'news': 4468,
 'job': 3611,
 'fifth': 2659,
 'woozles': 7059,
 'weasels': 6906,
 'exeter': 2549,
 'regret': 5283,
 'inform': 3464,
 'nhs': 4472,
 'mistake': 4250,
 'never': 4461,
 'actually': 768,
 'born': 1361,
 'report': 5328,
 'yor': 7160,
 'local': 3923,
 'hospital': 3298,
 '2b': 355,
 'terminated': 6294,
 'inconvenience': 3445,
 'house': 3310,
 'maid': 4061,
 'murderer': 4369,
 'coz': 1920,
 'murdered': 4368,
 'th': 6318,
 'january': 3575,
 'public': 5117,
 'govt': 3023,
 'instituitions': 3486,
 'closed': 1732,
 'including': 3442,
 'office': 4589,
 'understand': 6644,
 'minimum': 4220,
 'walk': 6848,
 '3miles': 438,
 'having': 3164,
 'movies': 4330,
 'laptop': 3781,
 'trouble': 6550,
 'while': 6970,
 'convincing': 1872,
 'twice': 6590,
 'neglect': 4445,
 'msgs': 4344,
 'read': 5217,
 'okay': 4602,
 'mrng': 4336,
 'write': 7084,
 'kate': 3671,
 '1apple': 302,
 'doctor': 2239,
 '1tulsi': 316,
 'leaf': 3818,
 'cancer': 1547,
 '1lemon': 309,
 'fat': 2618,
 '1cup': 304,
 'milk': 4209,
 'bone': 1343,
 'problms': 5062,
 'litres': 3905,
 'watr': 6889,
 'diseases': 2213,
 'snd': 5818,
 'ths': 6390,
 'whom': 6976,
 'care': 1563,
 'classes': 1712,
 'due': 2340,
 'dodgey': 2241,
 'expecting': 2559,
 'tomo': 6465,
 'recovery': 5260,
 'yay': 7135,
 'finally': 2681,
 'lol': 3937,
 'missed': 4241,
 'cinema': 1700,
 'trip': 6544,
 'flaky': 2715,
 'parent': 4751,
 'snot': 5821,
 'supposed': 6150,
 'child': 1674,
 'support': 6147,
 'ride': 5384,
 'age': 821,
 'anyway': 956,
 'hurt': 3353,
 'unintentional': 6658,
 'nonetheless': 4510,
 'competition': 1801,
 'yes': 7146,
 'completely': 1808,
 'form': 2781,
 'clark': 1709,
 'utter': 6726,
 'waste': 6877,
 'rumour': 5448,
 'buy': 1491,
 'apartment': 960,
 'brought': 1443,
 'gmw': 2971,
 'ltd': 4002,
 'connected': 1843,
 'congratulations': 1841,
 'either': 2406,
 '500': 508,
 'cd': 1598,
 'gift': 2948,
 'vouchers': 6816,
 '100': 233,
 'weekly': 6926,
 'draw': 2300,
 'music': 4372,
 '87066': 652,
 'tncs': 6442,
 'ldew': 3811,
 'com1win150ppmx3age16': 1779,
 'nosy': 4526,
 'guess': 3076,
 'idk': 3388,
 'over': 4697,
 'reacting': 5215,
 'freaked': 2806,
 'forgot': 2779,
 'show': 5696,
 'none': 4509,
 'nowhere': 4541,
 'ikno': 3399,
 'doesdiscount': 2243,
 'shitinnit': 5670,
 'yck': 7136,
 'dudette': 2339,
 'been': 1223,
 'missing': 4243,
 'early': 2360,
 'nightnight': 4483,
 'too': 6479,
 'stressfull': 6050,
 'always': 891,
 'laugh': 3797,
 'add': 770,
 'years': 7139,
 'surely': 6154,
 'adds': 777,
 'ni8': 4473,
 'swt': 6191,
 'dreams': 2304,
 'attempt': 1066,
 '1000call': 235,
 '09071512432': 215,
 '300603t': 403,
 'csbcm4235wc1n3xx': 1967,
 'callcost150ppmmobilesvary': 1521,
 'max': 4130,
 'thanks': 6323,
 'thangam': 6321,
 'cherthala': 1666,
 'case': 1579,
 'cochin': 1755,
 'bfore': 1266,
 'start': 5979,
 'shall': 5638,
 'reach': 5211,
 'accordingly': 746,
 'tmorow': 6435,
 'engaged': 2441,
 'ans': 933,
 'wot': 7077,
 'wear': 6903,
 'shirts': 5667,
 'jumpers': 3644,
 'hat': 3148,
 'belt': 1248,
 'cribbs': 1949,
 'blank': 1304,
 'trying': 6565,
 'serious': 5607,
 ...}

In [39]:
# convert to numpy array

x_train_np = x_train_cv.toarray()
x_train_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [40]:
# Build machine learning model using naive bayes model

from sklearn.naive_bayes import MultinomialNB

In [41]:
model = MultinomialNB()

In [42]:
model.fit(x_train_cv, y_train)

MultinomialNB()

In [43]:
x_test_cv = v.transform(x_test)

In [47]:
from sklearn.metrics import classification_report

y_pred = model.predict(x_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1448
           1       0.96      0.91      0.93       224

    accuracy                           0.98      1672
   macro avg       0.97      0.95      0.96      1672
weighted avg       0.98      0.98      0.98      1672

In [48]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

**using sklearn pipeline**

In [50]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])
clf

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [51]:
clf.fit(x_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [55]:
y_pred = clf.predict(x_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1448
           1       0.96      0.91      0.93       224

    accuracy                           0.98      1672
   macro avg       0.97      0.95      0.96      1672
weighted avg       0.98      0.98      0.98      1672

# Bag of words: Exercises

In [56]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from  sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

In [65]:
#1. read the data provided in the same directory with name 'movies_sentiment_data.csv' and store it in df variable
dataset = pd.read_csv('movies_sentiment_data.csv')

#2. print the shape of the data
print(dataset.shape)

#3. print top 5 datapoints
dataset.head()

(19000, 2)

                                              review sentiment
0  I first saw Jake Gyllenhaal in Jarhead (2005) ...  positive
1  I enjoyed the movie and the story immensely! I...  positive
2  I had a hard time sitting through this. Every ...  negative
3  It's hard to imagine that anyone could find th...  negative
4  This is one military drama I like a lot! Tom B...  positive

In [66]:
#creating a new column "Category" which represent 1 if the sentiment is positive or 0 if it is negative

dataset['Category'] = dataset['sentiment'].apply(lambda x: 1 if x == 'positive' else 0)
dataset.head()

                                              review sentiment  Category
0  I first saw Jake Gyllenhaal in Jarhead (2005) ...  positive         1
1  I enjoyed the movie and the story immensely! I...  positive         1
2  I had a hard time sitting through this. Every ...  negative         0
3  It's hard to imagine that anyone could find th...  negative         0
4  This is one military drama I like a lot! Tom B...  positive         1

In [67]:
#check the distribution of 'Category' and see whether the Target labels are balanced or not.
dataset['Category'].value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [77]:
#Do the 'train-test' splitting with test size of 20%
from sklearn.model_selection import train_test_split

x_train1, x_test1, y_train1, y_test1 = train_test_split(dataset.review, dataset.Category, test_size=0.2)

In [78]:
x_train1[0]

"I first saw Jake Gyllenhaal in Jarhead (2005) a little while back and, since then, I've been watching every one of his movies that arrives on my radar screen. Like Clive Owen, he has an intensity (and he even resembles Owen somewhat) that just oozes from the screen. I feel sure that, if he lands some meaty roles, he'll crack an Oscar one day...<br /><br />That's not to denigrate this film at all.<br /><br />It's a fine story, with very believable people (well, it's based upon the author's early shenanigans with rocketry), a great cast \x96 Chris Cooper is always good, and Laura Dern is always on my watch list \x96 with the appropriate mix of humor, pathos, excitement...and the great sound track with so many rock n roll oldies to get the feet tapping.<br /><br />But, this film had a very special significance for me: in 1957, I was the same age as Homer Hickham; like him, I looked up at the night stars to watch Sputnik as it scudded across the blackness; like Homer also, I experimented with rocketry in my backyard and used even the exact same chemicals for fuel; and like Homer, I also had most of my attempts end in explosive disaster! What fun it was...<br /><br />I didn't achieve his great (metaphorical and physical) heights though. But, that's what you find out when you see this movie.<br /><br />Sure, it's a basic family movie, but that's a dying breed these days, it seems. Take the time to see it, with the kids: you'll all have a lot of good laughs."

Exercise 1 : using sklearn pipeline module create a classification pipeline to classify the movie review's positive or negative.

1. use CountVectorizer for pre-processing the text.
2. use Random Forest as the classifier with estimators as 50 and criterion as entropy.
3. print the classification report.

In [79]:
#1. create a pipeline object
clf_random_forest = Pipeline([
    ('vectorizer', CountVectorizer()),                                
    ('random_forest', (RandomForestClassifier(n_estimators=50, criterion='entropy')))
])

#2. fit with X_train and y_train
clf_random_forest.fit(x_train1, y_train1)

#3. get the predictions for X_test and store it in y_pred
y_pred1 = clf_random_forest.predict(x_test1)

#4. print the classfication report
print(classification_report(y_test1, y_pred1))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84      1925
           1       0.83      0.84      0.84      1875

    accuracy                           0.84      3800
   macro avg       0.84      0.84      0.84      3800
weighted avg       0.84      0.84      0.84      3800

Exercise 2 : using sklearn pipeline module create a classification pipeline to classify the movie reviews positive or negative..

1. use CountVectorizer for pre-processing the text.
2. use KNN as the classifier with n_neighbors of 10 and metric as 'euclidean'.
3. print the classification report

In [82]:
clf_KNN = Pipeline([
    ('vectorizer', CountVectorizer()),                                
     ('KNN', (KNeighborsClassifier(n_neighbors=10, metric = 'euclidean')))
])

#2. fit with X_train and y_train
clf_KNN.fit(x_train1, y_train1)


#3. get the predictions for X_test and store it in y_pred
y_pred2 = clf_KNN.predict(x_test1)


#4. print the classfication report
print(classification_report(y_test1, y_pred2))

              precision    recall  f1-score   support

           0       0.65      0.64      0.65      1925
           1       0.64      0.64      0.64      1875

    accuracy                           0.64      3800
   macro avg       0.64      0.64      0.64      3800
weighted avg       0.64      0.64      0.64      3800

Exercise 3 : using sklearn pipeline module create a classification pipeline to classify the movie reviews positive or negative..

1. use CountVectorizer for pre-processing the text.
2. use Multinomial Naive Bayes as the classifier.
3. print the classification report

In [83]:
#1. create a pipeline object
clf_multi = Pipeline([      
     ('vectorizer', CountVectorizer()),   
      ('Multi NB', MultinomialNB())   #using the Multinomial Naive Bayes classifier 
])


#2. fit with X_train and y_train
clf_multi.fit(x_train1, y_train1)


#3. get the predictions for X_test and store it in y_pred
y_pred3 = clf_multi.predict(x_test1)


#4. print the classfication report
print(classification_report(y_test1, y_pred3))

              precision    recall  f1-score   support

           0       0.84      0.88      0.86      1925
           1       0.87      0.83      0.85      1875

    accuracy                           0.86      3800
   macro avg       0.86      0.86      0.86      3800
weighted avg       0.86      0.86      0.86      3800